# Generated by Django 5.1.3 on 2024-11-08 18:41

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_superuser(apps, schema_editor):
    User = apps.get_model("auth", "User")
    User.objects.create(
        username="viamericas",
        email="viamericas@example.com",
        password=make_password("holamundo123"),
        is_superuser=True,
        is_staff=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
