# Generated by Django 5.1.3 on 2024-11-09 13:29

from django.db import migrations


def add_default_data(apps, schema_editor):
    Category = apps.get_model("reservations", "Category")
    Speaker = apps.get_model("reservations", "Speaker")

    Category.objects.get_or_create(
        name="Conferencia",
        defaults={"description": "Categoría para conferencias generales."},
    )

    Category.objects.get_or_create(
        name="Capacitación",
        defaults={"description": "Categoría para capacitaciones."},
    )

    Category.objects.get_or_create(
        name="Clase magistral",
        defaults={"description": "Categoría para clases magistrales."},
    )

    speakers = [
        {
            "first_name": "Albert",
            "last_name": "Einstein",
            "email": "einstein@example.com",
            "bio": "Físico teórico, conocido por la teoría de la relatividad.",
        },
        {
            "first_name": "Marie",
            "last_name": "Curie",
            "email": "curie@example.com",
            "bio": "Científica polaca-francesa, pionera en el campo de la radiactividad.",
        },
        {
            "first_name": "Nikola",
            "last_name": "Tesla",
            "email": "tesla@example.com",
            "bio": "Inventor, ingeniero eléctrico y mecánico, conocido por sus contribuciones al desarrollo de sistemas eléctricos de corriente alterna.",
        },
    ]

    for speaker_data in speakers:
        Speaker.objects.get_or_create(**speaker_data)


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_create_superuser"),
    ]

    operations = [
        migrations.RunPython(add_default_data),
    ]
