# Generated by Django 5.1.3 on 2024-11-09 14:01

from django.db import migrations


def create_default_attendees(apps, schema_editor):
    Attendee = apps.get_model("reservations", "Attendee")

    attendees = [
        {"first_name": "John", "last_name": "Doe", "email": "johndoe@example.com"},
        {"first_name": "Jane", "last_name": "Smith", "email": "janesmith@example.com"},
        {
            "first_name": "Alice",
            "last_name": "Johnson",
            "email": "alicejohnson@example.com",
        },
        {"first_name": "Bob", "last_name": "Brown", "email": "bobbrown@example.com"},
    ]

    for attendee_data in attendees:
        Attendee.objects.get_or_create(**attendee_data)


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_add_default_data"),
    ]

    operations = [
        migrations.RunPython(create_default_attendees),
    ]
